lidar_tf_position_publisher_node:
  ros__parameters:
    global_frame: world
    lidar_frame: innoviz
    lidar_pitch: 0.0
    lidar_roll: 0.0
    lidar_yaw: 0.0
    lidar_x: 0.0
    lidar_y: 0.0
    lidar_z: 1.7
    tf_hz: 1.0
