# Image dimensions
BEV_HEIGHT: 608
BEV_WIDTH: 608

# Point cloud boundaries (in meters)
boundary:
  minX: 0
  maxX: 30
  minY: -15
  maxY: 15
  minZ: -2
  maxZ: 4

# Discretization factor (meters per pixel)
DISCRETIZATION: 0.1